### ISSUE TITLE
Use a real webserver instead of Django's runserver for `armstrong runserver`

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#10]
There's no reason to use Django's server.  `armstrong runserver` could just as easily use [Gunicorn](http://gunicorn.org/) or something else.  @tswicegood got a local copy working relatively easily, but we need to address possible issues with people not wanting to/having the ability to install things such as Gunicorn.

**Comment by tswicegood** [comment]
Ideally this uses `entry_points` to allow adding different backend servers.  By default we could use Django's built-in `runserver` command, but also have the ability to use Gunicorn, cherry.py, or something all together different.

**Comment by joncotton** [comment]
Nice idea, but three years and no progress later...closing. (We can always reopen)
