### ISSUE TITLE
Get this error during intallation

### ISSUE THREAD

**Issue by aimechris** [armstrong/armstrong#102]
Collecting armstrong.core.arm-content<1.1,>=1.3.1 (from armstrong)

> Could not find a version that satisfies the requirement armstrong.core.arm-content

**Comment by Jbonnett** [comment]
This project is mostly dead and unmaintained, You should not start a NEW
project on armstrong. If you have something old that has stopped working,
let us know and maybe one of the old hands will help out.

**Comment by joncotton** [comment]
Ditto, sadly. Some of the more recently updated Armstrong components are standalone and usable though not updated for the latest Django versions. What is your use case @aimechris? What organization?
