### ISSUE TITLE
Update links on main website to point to armstrong user, not repo

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#11]

**Comment by tswicegood** [comment]
@tinio, can you update this.  Got pinged privately with a "where's all of the code" because we deep link from the site into the main `armstrong` repository.  Makes sense to point people to the organization page rather than the repo since it can be a bit unnerving.

**Comment by tinio** [comment]
@tswicegood, There are two links to github right now, one goes to:

http://github.com/armstrong

the other goes to the contributing page:

http://github.com/armstrong/armstrong/wiki/Contributing

Did you mean that I should change the contributing link to just http://github.com/armstrong as well?

**Comment by tswicegood** [comment]
Hmm...  Maybe this was a bogus report.  I got a report that we had a link into the repo, not the organization.  Guess if we don't, we're ok.
