### ISSUE TITLE
Set SECRET_KEY to a sane default

### ISSUE THREAD

**Issue by dmclain** [armstrong/armstrong#13]
We can pretty easily create some crypto-gibberish and add it via the template system. That would be better than assigning ''

**Comment by tswicegood** [comment]
Do we not already do that?  I thought we were using the same pattern that Django uses to generate that string.

**Comment by dmclain** [comment]
We're just setting it to the empty string
https://github.com/armstrong/armstrong.cli/blob/master/armstrong/cli/templates/standard/settings/defaults.py#L82

Compared to:
https://github.com/django/django/blob/master/django/core/management/commands/startproject.py#L32

**Comment by dmclain** [comment]
Apparently I don't know how to use GH

**Comment by tswicegood** [comment]
Gah.  I love it when Django has these useful little functions tucked away inside completely unrelated code.  Copy-n-paste I guess. :-/

**Comment by tswicegood** [comment]
I'm marking this as a bug.  We need to roll a 1.0.1 release with this change in at some point very soon.

**Comment by tswicegood** [comment]
Fixed this in [armstrong/armstrong.cli v1.0.1](https://github.com/armstrong/armstrong.cli/commit/4af8761d7ea817466d963cadda5961cda9bf9166)
