### ISSUE TITLE
Django 1.4 and armstrong.dev do not get along.

### ISSUE THREAD

**Issue by Jbonnett** [armstrong/armstrong#17]
https://gist.github.com/c363c0c34a76b8308f2b

Thats the error from alerts but any of the fab tests that use the VirtualDjango facility have the same problem.

**Comment by tswicegood** [comment]
@Jbonnett: do you have the test case that was causing this and the command you were executing?  I assume a straight `fab test`?

**Comment by Jbonnett** [comment]
Yep. Its fab test on anything that using virtual django. Basically anything but the audio and video back ends. The only trick is to set up django 1.4 in your dev env. But that is as simple as checking it out  and putting it in your python path.

**Comment by tswicegood** [comment]
All of Armstrong works with both Django 1.3.1 and 1.4.
