### ISSUE TITLE
Tests fail inside a project

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#18]
Currently if you try to run the tests for Armstrong projects that have a `_support` app, they fail.  This is a false failure.  All tests do pass in isolation, but these tests fail because of a lack of their `<name>_support` app being installed.

Apps in the current `11.09.0` release that are effected:
- armstrong.core.arm_access
- armstrong.core.arm_content
- armstrong.core.arm_layout
- armstrong.core.arm_sections.
- armstrong.core.arm_wells
- armstrong.apps.related_content

armstrong.apps.images fails for a different reason, and it's something I'm (@tswicegood) looking into.

**Comment by tswicegood** [comment]
My current thought process is to move all tests into their own app for testing.  For example, `armstrong.core.arm_wells` would have an `armstrong.core.arm_wells.arm_wells_tests`.  This removes the conflict and keeps from running what is essentially library code in your test suite unless you specifically opt-in.

**Comment by joncotton** [comment]
Closing. With ArmDev 2.0 universally using Django 1.6's test runner, we can easily move the tests into the root directory of the project. With that and `prune tests` in the Manifest, we no longer ship tests. The above listed apps may still suffer this problem, but there's a solution now. Take a look at the post-1.3/pre-1.4 work on `armstrong.core.arm_layout` for an example.

Oh and for thoroughness, prior to Django 1.6, the test runner automatically ran the tests for everything in INSTALLED_APPS. That doesn't happen anymore so users on Django 1.6+ shouldn't see this issue.
