### ISSUE TITLE
Point to a sample salesforce apps.crm backend from The Bay Citizen

### ISSUE THREAD

**Issue by tinio** [armstrong/armstrong#21]
Looks like work is already started on this:
https://github.com/Jbonnett/armstrong.apps.crm.backends.salesforce

Simply adding issue to keep track.

**Comment by tswicegood** [comment]
FWIW, the plan at the @TexasTribune is to build the SugarCRM inside the `texastribune` namespace.  I'm a fan of doing that with the SalesForce too.  I don't have any interest in maintaining a SalesForce backend, and I imagine you guys don't have an interest in maintaining a SugarCRM backend. :-)

**Comment by tinio** [comment]
@tswicegood completely agree.  I'll rename the issue to convey that we are pointing to a `sample` implementation of salesforce from The Bay Citizen.

**Comment by joncotton** [comment]
This isn't going to happen.

**Comment by Jbonnett** [comment]
Yep. Totally isnt.
