### ISSUE TITLE
hardcoded value in the AJAX URL for initVisualSearch.valueMatches()

### ISSUE THREAD

**Issue by joncotton** [armstrong/armstrong#39]
The [$.getJSON()](https://github.com/armstrong/armstrong.hatband/blob/master/armstrong/hatband/static/generickey.js#L76) call in hatband/static/generickey.js initVisualSearch.valueMatches() is hard-coded to use _'/admin/'_. This should somehow detect (or be given) the actual base URL to use.

On the Django side the URL routing works fine.
Say the route is setup in `urls.py` like:

```
(r'^different_admin/',                      include(admin.site.urls)),
```

Doing this gives the correct result:

```
>>> reverse("admin:articles_article_search", args=("articles", "article"))
'/different_admin/articles/article/search/'
```

**Comment by tswicegood** [comment]
Thanks for the report.  It's on the short-list of things to get out ASAP.

**Comment by dmclain** [comment]
I'd recommend refactoring the code so that there's a single endpoint for searching that takes in parameters specifying the app and model that should be searched. That endpoint can simply pass through to the existing search view, but it seems broken to be building the search url from information passed in from the facet rather than just hitting a predetermined url with arguments. I'd also suggest we stop parsing out the app_name and model from the url, since it's odd that you can't just say `reverse("admin:articles_article_search")`

**Comment by joncotton** [comment]
I agree that handing a single search function arguments is better. That means we can reverse it before use. Right now the URL can't be reversed because we don't know `app_label` and `model` until the facet search is complete e.g. we don't know until the JavaScript code.

The reason we call a URL based on `app_label` and `model` is because the method that handles it (`generic_key_modelsearch()`) passes off to the Admin `changelist_view()` that requires those two params.

We're already admin wrapping the view; do we need anything from ChangeList? We don't need actions, POST handling, or Forms. Why not just `@json_response` a QuerySet?

**Comment by joncotton** [comment]
I see now -- `changelist_view()` uses `django.contrib.admin.views.main.ChangeList`. ChangeList is searchable. When we pass that `q` GET parameter, it's automatically used to filter the JSON results that are returned. Nice!

But ChangeList works entirely off the `request` variable so that gets us back to the start of the issue with `app_label` and `model` required in the URL.

Will investigate further...
**Update:** and ChangeList requires 12 params to instantiate. hah
I feel like I'm following your Indiana Jones footsteps through the temple. I can see you already tried this based on your import of `ChangeList as DjangoChangeList`.

**Comment by dmclain** [comment]
It's not required in the url it just needs to be an argument. Rather than::

```
url(r"^(?P<app_label>%s)/(?P<model_name>%s)/search/" % (model._meta.app_label, model._meta.module_name),
                self.admin_view(self.generic_key_modelsearch),
                name="%s_%s_search" % (
                        model._meta.app_label,
                        model._meta.module_name))
```

Something akin to::

```
url(r"^%s/%s/search/" % (
                        model._meta.app_label, model._meta.module_name),
                self.admin_view(self.generic_key_modelsearch),
                {'app_label': model._meta.app_label,
                 'model_name': model._meta.module_name},
                name="%s_%s_search" % (
                        model._meta.app_label,
                        model._meta.module_name))
```

**Comment by joncotton** [comment]
Resolved in armstrong.hatband v1.2.0
