### ISSUE TITLE
South should be in the INSTALLED_APPS by default

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#40]
We should have [South](http://south.aeracode.org/) listed in the `INSTALLED_APPS` by default and it should be in all of the project level requirements files.

**Comment by tswicegood** [comment]
This touches all of the templates and requires the demo data to be re-generated with the migration data there.

**Comment by joncotton** [comment]
Demo situation aside, South should be a per-project requirement/setting. Some components just don't need South. This Issue is pretty old so...closing.
