### ISSUE TITLE
Upgrade various packages to use reversion 1.5.1

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#41]
We currently have two sets of dependencies: a few apps say they want 1.3.3, while others want 1.4.  We need to upgrade all of them so they're on the same version.

Side benefit, the tests for reversion 1.3.3 currently don't pass in an Armstrong project.

**Comment by joncotton** [comment]
django-reversion 1.8 is current. I'm closing this issue because the effected components are, at this point, so very out of date that they need a lot more help that this.
