### ISSUE TITLE
extend Section.slug to 255 characters

### ISSUE THREAD

**Issue by martey** [armstrong/armstrong#43]
armstrong.core.arm_sections.models.Section uses the [default Django SlugField](https://docs.djangoproject.com/en/dev/ref/models/fields/#slugfield) to represent its slug. This slug's default max_length is only 50 characters.

This can lead to issues when importing from external databases. [WordPress' section slugs](http://codex.wordpress.org/Database_Description#Table:_wp_terms) have a maximum length of 200 characters, which can cause errors.

**Comment by tswicegood** [comment]
Fair point.  We'll have to coordinate releases on this one though, because everything that relies on `armstrong.core.arm_content` is going to need a migration.  Something we can definitely do prior to the 11.12 release, though.

**Comment by joncotton** [comment]
We use the default `SlugField` for both [Section](https://github.com/armstrong/armstrong.core.arm_sections/blob/v1.5.6/armstrong/core/arm_sections/models.py#L45) and [ContentBase](https://github.com/armstrong/armstrong.core.arm_content/blob/v1.3.5/armstrong/core/arm_content/models.py#L33-L34). I think changing the `max_length` from the default 50 to 200 is a good idea. Thanks @martey for the doc links and issue.

I'll make this change for ArmSections soon (that's the component I'm currently upgrading). ArmContent will happen...later.
