### ISSUE TITLE
Template tags handle StopIteration incorrectly

### ISSUE THREAD

**Issue by niran** [armstrong/armstrong#50]
`StopIteration` raised within a template tag is caught by Django, which raises a `TemplateSyntaxError`. This makes `render_iter`'s `StopIteration` handling useless. This also means any tag that calls `iterator.next()` (i.e. `render_next` and `render_remainder`, the latter of which already does) needs to handle `StopIteration`.

**Comment by tswicegood** [comment]
@niran, @dmclain: any idea how to best proceed on this?

**Comment by dmclain** [comment]
I'm having trouble reproducing the TemplateSyntaxError with django 1.3.1.

There's a test case that tries to emulate this case, but it doesn't actually invoke the Django template renderer, just the RenderIterNode's render method https://github.com/armstrong/armstrong.core.arm_layout/blob/master/armstrong/core/arm_layout/tests/templatetags/layout_helpers.py#L256-267

**Comment by joncotton** [comment]
Closing as not longer applicable. Test coverage has been increased and tests have changed to use the template tag/renderer (not just the Node) in armstrong/armstrong.core.arm_layout#12 which is slated for release in v1.3.0. (Also this issue is old and hasn't cropped up since.)
