### ISSUE TITLE
Allow {% render_model object "layout_name" with width="160" only %}

### ISSUE THREAD

**Issue by crccheck** [armstrong/armstrong#52]
I'd like the ability to use the sugar that comes with the `{% include %}` tag with `{% render_model %}`.

Current use case is I've got a layout with an image, and I'd like to pass in an optional width for the layout to use. The 'ole workaround is just use the `with` tag around the block. I really just care about getting `with` but if we're going to add that we might as well add `only` to make it match up with `include`.

Questions:
Is this something you see as useful? Did we want to reserve additional parameters to `render_model` for something else? These are the questions that keep me up at night.

Current Include Tag Syntax:
https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatetag-include
Current Include Tag Source:
https://github.com/django/django/blob/master/django/template/loader_tags.py#L219

**Comment by niran** [comment]
This has come up before, and seems worthwhile to me. `render_model` is a fancy `include` tag, so paralleling it as much as possible is valuable. Pull requests welcome.

**Comment by tswicegood** [comment]
Ditto what @niran said.  I'm not sure how valuable `only` is because it would be to be "only + `object`", but if ya want to add it I see no reason to keep it out of Armstrong.

**Comment by tswicegood** [comment]
@crccheck Any interest in taking a stab at this for v12.06?

**Comment by crccheck** [comment]
Sure.

**Comment by niran** [comment]
This is a very low priority feature, so let's either do this on the side or make sure the important things get tackled before taking this on.

**Comment by tswicegood** [comment]
Yeah -- it's also a very low time feature.  Let's keep it in here and hopefully we can get it in before the next release.

**Comment by joncotton** [comment]
Slated for release in v1.3.0 so I'm closing.

**Comment by crccheck** [comment]
![](http://images.wikia.com/adventuretimewithfinnandjake/images/f/f3/DANCING_COOKIE.gif)
