### ISSUE TITLE
Rename arm_layout to arm_inlines

### ISSUE THREAD

**Issue by epicserve** [armstrong/armstrong#55]
I know this isn't a "big deal" or anything, but I really wish arm_layout was called arm_inlines. Maybe it's just semantics, but all the templates that go in layout app aren't templates for a site layout but are really templates for inline elements that get placed on a page.

**Comment by tswicegood** [comment]
@epicserve thanks for the feedback on this.  Right now all this app does is provide the various `render_%` template tags, but it's longer-term goal is to provide a lot more regarding layout of the site.  With that in mind, I think we should keep the name as-is.
