### ISSUE TITLE
The card_number field should not be pre-populated on error

### ISSUE THREAD

**Issue by niran** [armstrong/armstrong#61]
Most sites don't show the data again, instead you must re-enter the entire card number.

**Comment by tswicegood** [comment]
Define "persist" here?  To be clear, _nothing_ with the credit card information is stored during the entire process.

**Comment by niran** [comment]
If someone has a template that is essentially `{{ form }}`, things should just work. That is, we should proactively remove the credit card information from the form when an error has occurred. Does that sound reasonable?

**Comment by tswicegood** [comment]
I think that's a reasonable feature to have, but I also think it should be configurable.  Should be easy enough to do, though.

**Comment by tswicegood** [comment]
This is in the 1.0.0 release.
