### ISSUE TITLE
Remove apps.content dependency from apps.embedded_video

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#65]
There is no real reason for this dependency.  We need to remove it.  Note that we may break BC by doing this, but `apps.embedded_video` is pre-1.0, so breaking BC is ok if needed.

**Comment by joncotton** [comment]
Closing and using a new tag of "yes_but_irrelevant". This is definitely a valid Issue, but this package is unmaintained and untouched for 3 years. Besides, [armstrong.apps.embeds](https://github.com/armstrong/armstrong.apps.embeds) is a better solution to handling embedded/external content of any nature.
