### ISSUE TITLE
Add comments to the standard template

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#7]
It's a good idea to show using Django's built in comments app inside the demo project.  It's easy enough for people to switch out to other commenting systems if they want, but having comments baked in would be a good start.

**Comment by joncotton** [comment]
`django.contrib.comments` is now deprecated. It's available as an external project but it's going away. So this issue is no longer relevant. Could we add an example for Disqus? Yes. Are we? Ya right.

**Comment by Jbonnett** [comment]
Threaded comments is still worth using,
