### ISSUE TITLE
Invalid Django Requirements

### ISSUE THREAD

**Issue by pizzapanther** [armstrong/armstrong#71]
Several apps have conflicting requirements such as:
armstrong.core.arm_access-1.0.6-py2.7.egg-info/requires.txt:Django==1.3.1,==1.4

On Gondor this causes 1.3 to get installed when I wanted 1.4.

Most likely the requirement should be:
Django>=1.3.1,Django<=1.4
or
Django>=1.3.1

**Comment by tswicegood** [comment]
This is most likely a bug on Gondor and (totally guessing here) either an outdated pip or a bug in a PyPI caching layer.

`Django==1.3.1,==1.4` means that either Django 1.3.1 or Django 1.4 can be installed and will work.  The preference is the higher version unless that causes a conflict somewhere else or Django 1.3.1 is already installed.

**Comment by tswicegood** [comment]
I've verified that this isn't a issue on our end.  Here's an install on a clean virtual environment.

```
12:50:45 ○ [tswicegood@travis.local] (py: test-issue-71) 
~/work/armstrong
 $ pip --version
pip 1.1 from /Users/tswicegood/.virtualenvs/test-issue-71/lib/python2.7/site-packages/pip-1.1-py2.7.egg (python 2.7)

12:50:54 ○ [tswicegood@travis.local] (py: test-issue-71) 
~/work/armstrong
 $ pip install Django==1.3.1,==1.4
Downloading/unpacking Django==1.3.1,==1.4
  Downloading Django-1.4.tar.gz (7.6Mb): 7.6Mb downloaded
  Running setup.py egg_info for package Django

Installing collected packages: Django
  Running setup.py install for Django
    changing mode of build/scripts-2.7/django-admin.py from 644 to 755

    changing mode of /Users/tswicegood/.virtualenvs/test-issue-71/bin/django-admin.py to 755
Successfully installed Django
Cleaning up...

12:52:00 ○ [tswicegood@travis.local] (py: test-issue-71) 
~/work/armstrong
 $ pip freeze
Django==1.4
distribute==0.6.24
wsgiref==0.1.2
```

**Comment by pizzapanther** [comment]
Thanks for the investigation.

It is working on my dev environment so I concur.

If it is because of an outdated pip maybe it should be changed to support older versions?

**Comment by tswicegood** [comment]
I don't think this is an issue that we can actually fix, nor as I think about it do I really think it's a bug in an older version pip/distutils as version specs are pretty well defined.

Did you have a working virtualenv already?  My unsubstantiated hunch is that Django 1.3.1 was already there so that's what it used.  Can you try with an entirely clean Gondor instance/site?

**Comment by pizzapanther** [comment]
I had the project working with 1.4 originally and when I redeployed it failed.  From now on it installs 1.3.  Haven't tried to deploy on a new server, but don't really want to because that would mean migrating the db and files.

**Comment by niran** [comment]
Is there a way to explicitly set a `Django==1.4` requirement for your project itself on Gondor? Hopefully that would override the versions specified in dependencies.

**Comment by pizzapanther** [comment]
i had done that already in my project requirements.  Was my first line.
