### ISSUE TITLE
Arm well's .get_current() should resemble .get()

### ISSUE THREAD

**Issue by crccheck** [armstrong/armstrong#74]
So the issue I'm running into is: I want to use `.get_current()` but I only have the slug, not the title. What if `.get_current`, instead of expecting `title`, just took arbitrary kwargs it passed onto the .filter() inside? Code would change from `well.objects.get_current('Test Well')` to `well.objects.get_current(title='TestWell')`, and for comparison, `well.objects.get(title='TestWell')`.

It's a backwards incompatible change, but could be written so it wasn't by grabbing args and kwargs and checking types or maybe just checking for the existence of args.

**Comment by niran** [comment]
Agreed. Easy to make it backwards compatible.
