### ISSUE TITLE
Demo paywall code usage in standard template

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#8]
The standard template needs to show off how to use the paywall to restrict content.

**Comment by tswicegood** [comment]
@dmclain: I've assigned this one to you since you know that code the best.  If you're looking for a [yak to shave](http://en.wiktionary.org/wiki/yak_shaving), this would be a good case for a separate template that you could specify via an `armstrong init --template=standard_paywall <some dir>`.

**Comment by dmclain** [comment]
you want it separate from the demo project?

**Comment by tswicegood** [comment]
@dmclain: it'd be cool if there was a separate template for generating a paywalled site.  We had talked about the idea of the manifest allowing an "extends" command so one template could override certain parts of another template.  This would be a place for that.

Again though, it's in the "nice to have" category, not something that's needed.

**Comment by dmclain** [comment]
This happened in a3560b4cd8ab89892aecf57c0a740c661ed7f67e
