### ISSUE TITLE
VisualSearch can overwrite existing scripts

### ISSUE THREAD

**Issue by joncotton** [armstrong/armstrong#82]
VisualSearch via the `GenericKeyWidget` Media includes a [dependencies.js](https://github.com/armstrong/armstrong.hatband/blob/master/armstrong/hatband/widgets/visualsearch.py#L14) file. That [file](https://github.com/armstrong/armstrong.hatband/blob/master/armstrong/hatband/static/visualsearch/dependencies.js) contains jQuery, Sizzle CSS Selector, jQuery UI and jQuery UI Widget. All of those could stomp on versions already imported through other means.

In the particular case where I discovered this, I already had jQuery along with a bunch of jQuery plugins. Reimporting jQuery here obliterated the plugins causing errors besides just being unnecessary.

**Comment by tswicegood** [comment]
This is an issue that we can't really address any further than we have.  The latest `armstrong.hatband` uses the `ARMSTRONG_ADMIN_PROVIDE_STATIC` setting to determine whether it should provide any static files such as JS or CSS.  It defaults to `True`, but setting it to `False` means none of the media will be loaded.

We currently deploy the Tribune with `ARMSTRONG_ADMIN_PROVIDE_STATIC=False` as the setting.

**Comment by joncotton** [comment]
`PROVIDE_STATIC` is a good feature and I think we'll use it here to.
However, we could test for jQuery first before loading it. Simple `window.jQuery` test or `yepnope` loading. There are other options.
