### ISSUE TITLE
You can kill your site by creating two sections with the same slug

### ISSUE THREAD

**Issue by newz2000** [armstrong/armstrong#84]
Hi, ran into a funny problem tonight.

If a user adds a section that has the same slug as another section then the home page will fail to load because get_object_or_404(Section, slug) will return multiple results.

I can think of two behaviors that are better:
1. If the slug must be unique then enforce it at the model
2. Don't make the slug unique if it doesn't need to be.

In this example, a section was called "news" and it's slug was "news." It had some sub-sections, including a sub-section named "news" (i.e. it had it's parent set to news) and it had its slug set to news.

The user probably should have gotten a warning that the slug was a duplicate. Instead, he created the new section and left for the day and the site was down and no one knew why.

**Comment by joncotton** [comment]
It should be clarified, but the paradigm is to use the `full_slug` for uniqueness. `SimpleSectionView` does this with its [get_object_or_404](https://github.com/armstrong/armstrong.core.arm_sections/blob/f5d36900f7b0503a60a526fd70b57ecb91625fa0/armstrong/core/arm_sections/views.py#L19). We should **consider adding the unique constraint** to `full_slug` in the Model definition.

The Bay Citizen uses the Section model for a couple different purposes and we have duplicate slugs but never duplicate full_slugs. We also never nest beyond the second level (though deeper nesting would be fine). With a quick grep, I only see one case where we do section object lookup using only the `slug` but in that case the `parent` object is also known (and used in the query).

That's all fine in the code, but your problem happened with a **user creating a new section** in the admin and there's nothing to prevent duplicates. That would break our site as well. And is an excellent argument for a unique constraint on `full_slug`. This is our solution and may work for you. (We use `slug` but `full_slug` is also appropriate and maybe necessary for deeper nesting.)

1) [Proxy](https://docs.djangoproject.com/en/1.5/ref/models/options/#proxy) the `Section`model
2) Force uniqueness on the field (which triggers the same non-unique form errors):

```
def __init__(self, *args, **kwargs):
    super(Section, self).__init__(*args, **kwargs)
    self.__class__._meta.get_field('slug')._unique = True
```

3) Replace the Admin. In `admin.py`:

```
from django.contrib import admin
from armstrong.core.arm_sections.admin import SectionAdmin
from armstrong.core.arm_sections.models import Section as ArmSection

from .models import ProxySection

admin.site.unregister(ArmSection)
admin.site.register(ProxySection, SectionAdmin)
```
