### ISSUE TITLE
armstrongcms.org contains text touting not-yet-released features

### ISSUE THREAD

**Issue by martey** [armstrong/armstrong#96]
> Available out of the box, Armstrong has deep integration with social media sites such as Facebook and Twitter, search engine optimization, tools to manage memberships and subscriptions, and much more.

Because this "deep integration" is not (to my knowledge) available, this text is extremely confusing. I think it would be fine to state that such features are on the roadmap, but not to refer to them as being currently available.

**Comment by joncotton** [comment]
Totally agree. We will be talking about ArmstrongCMS.org over the next couple of days. The site has some marketing language that needs to be brought back to earth.

**Comment by Jbonnett** [comment]
Totally true. That site badly needs to be rewritten by someone who isn'ta
marketing drone.

**Comment by joncotton** [comment]
New site launched—`armstrong.github.io`—and the domain is re-pointed.
